### ISSUE TITLE
Operation not permitted. Stack dump not enabled.

### ISSUE THREAD

**Issue by KamillaPup** [Wonderfall/docker-rtorrent-flood#12]
First off, I am Docker stupid. I've worked with web servers before, but this is a new world for me. So if I missed something simple, don't be surprised. Just seeking help.

I've installed this from the Docker Catalog within Plesk using the new tag and when it started, I got the following errors:
```
> flood@1.0.0 start /usr/flood
> node server/bin/start.js

[?1049h[22;0;0t[1;24r(B[m[4l[?7h[?1h=[?25l[24;1H[?12l[?25h[?1049l[23;0;0t
[?1l>Caught internal_error: PollEPoll::modify(...) epoll_ctl(7, 1 -> 1, 0, [0x7fb5dda3df00:1]) = 1: Operation not permitted
Stack dump not enabled.
Flood server starting on http://undefined:3000.
```
Despite this, I was still able to load the welcome screen but when I went to create a user, it just hung and wouldn't load. I revisited the website and got ERR_CONNECTION_REFUSED.
![Screen Shot 2019-11-17 at 9 41 12 PM](https://user-images.githubusercontent.com/26353056/69023117-474fcf80-0983-11ea-9c6f-bfa323115191.png)
![Screen Shot 2019-11-17 at 9 41 19 PM](https://user-images.githubusercontent.com/26353056/69023119-49199300-0983-11ea-8b1a-909332719037.png)

**Comment by norfair00** [comment]
I Have Same Error

```
tt
Caught internal_error: PollEPoll::modify(...) epoll_ctl(9, 1 -> 1, 0, [0x7f7d09ba3e20:1]) = 1: Operation not permitted


Stack dump not enabled.


tt
Caught internal_error: PollEPoll::modify(...) epoll_ctl(9, 1 -> 1, 0, [0x7f20428d1e20:1]) = 1: Operation not permitted


Stack dump not enabled.


tt
Caught internal_error: PollEPoll::modify(...) epoll_ctl(9, 1 -> 1, 0, [0x7f6efe2a0e20:1]) = 1: Operation not permitted


Stack dump not enabled.


tt
Caught internal_error: PollEPoll::modify(...) epoll_ctl(9, 1 -> 1, 0, [0x7fddcb714e20:1]) = 1: Operation not permitted


Stack dump not enabled.


tt
Caught internal_error: PollEPoll::modify(...) epoll_ctl(9, 1 -> 1, 0, [0x7f6dba28ce20:1]) = 1: Operation not permitted


Stack dump not enabled.


tt
Caught internal_error: PollEPoll::modify(...) epoll_ctl(9, 1 -> 1, 0, [0x7f0c50bf6e20:1]) = 1: Operation not permitted


Stack dump not enabled.


tt
Caught internal_error: PollEPoll::modify(...) epoll_ctl(9, 1 -> 1, 0, [0x7f0cae866e20:1]) = 1: Operation not permitted


Stack dump not enabled.


tt
Caught internal_error: PollEPoll::modify(...) epoll_ctl(9, 1 -> 1, 0, [0x7f7e40eece20:1]) = 1: Operation not permitted


Stack dump not enabled.


tt
Caught internal_error: PollEPoll::modify(...) epoll_ctl(9, 1 -> 1, 0, [0x7f151f659e20:1]) = 1: Operation not permitted


Stack dump not enabled.
```

**Comment by Coosos** [comment]
Hi,

Did you add `tty: true` in your docker-compose?
https://github.com/Wonderfall/docker-rtorrent-flood#note

I had the same problem and following the readme correctly I fixed this same problem ^^
If that doesn't solve the problem, I can't help you more than that :(

example docker-compose

```
version: "3.8"
services:
  rtorrent:
    image: wonderfall/rtorrent-flood
    container_name: rtorrent
    restart: always
    environment:
      UID: ${PUID}
      GID: ${PGID}
    ports:
    - 3000:3000
    - 49184:49184
    - 49184:49184/udp
    volumes:
      - ${ROOT}/downloads/:/data:rw
      - ${ROOT}/flood-db/:/flood-db:rw
    tty: true
```
