### ISSUE TITLE
rtorrent keeps saying that the NFS disk is full

### ISSUE THREAD

**Issue by Treast** [Wonderfall/docker-rtorrent-flood#27]
I've bind the `/data` and `/flood-db` on my 2To NFS disk, but rtorrent keeps saying that the disk is full, and stop downloading torrents. And even on Flood, the disk seems full.

![image](https://user-images.githubusercontent.com/3629578/103473982-363c6a80-4d9f-11eb-88f3-73f8a85d0998.png)

I've tried to specified volumes as NFS, still don't work : 
```
version: '3.7'
services:
  flood:
    image: 127.0.0.1:5000/rtorrent-flood
    restart: always
    tty: true
    volumes:
      - type: volume
        source: plex_volume_movies
        target: /data
        volume:
          nocopy: true
      - type: volume
        source: plex_volume_db
        target: /flood-db
        volume:
          nocopy: true
    ports:
      - 4000:3000
      - 49184:49184
    environment:
      - FLOOD_SECRET=secretcodefloorthatshouldbeover30characters

volumes:
  plex_volume_movies:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.1.22,nolock,soft,rw"
      device: ":/plex/movies"
  plex_volume_db:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.1.22,nolock,soft,rw"
      device: ":/plex/db"
```

Do you have any idea how to fix it ? Thanks !
