### ISSUE TITLE
Can't seem to get working with traefik

### ISSUE THREAD

**Issue by peavers** [Wonderfall/docker-rtorrent-flood#4]
Having issues getting the WEBROOT value to work with traefik. If I launch the below, I can hit the domain at example.com/rutorrent... but it looks like Flood is trying to load static files from example.com ignoring the context path. 

```
  rutorrent:
    container_name: rutorrent
    image: wonderfall/rtorrent-flood
    restart: always
    environment:
    - TZ=${TZ}
    - PGID=${PGID}
    - PUID=${PUID}
    - WEBROOT=/rutorrent
    volumes:
    - ${USERDIR}/rutorrent:/config
    - ${DOWNLOADS}:/downloads
    logging:
      options:
        max-size: "2m"
        max-file: "5"
    networks:
    - traefik_proxy
    labels:
    - "traefik.enable=true"
    - "traefik.backend=rutorrent"
    - "traefik.frontend.rule=Host:${DOMAINNAME}; PathPrefix: /rutorrent"
    - "traefik.port=3000"
    - "traefik.docker.network=traefik_proxy"
    - "traefik.frontend.headers.SSLRedirect=true"
    - "traefik.frontend.headers.STSSeconds=315360000"
    - "traefik.frontend.headers.browserXSSFilter=true"
    - "traefik.frontend.headers.contentTypeNosniff=true"
    - "traefik.frontend.headers.forceSTSHeader=true"
    - "traefik.frontend.headers.SSLHost=valhalla.life"
    - "traefik.frontend.headers.STSIncludeSubdomains=true"
    - "traefik.frontend.headers.STSPreload=true"
    - "traefik.frontend.headers.frameDeny=true"
```

Have I missed anything obvious here?

**Comment by hergonoway** [comment]
Your post is old, but my container works with traefik so here's my docker-compose.yml in case you still need it.

```
version: '3'

services:
  flood:
    image: wonderfall/rtorrent-flood:latest
    container_name: Flood_V2
    networks:
      - proxy
    ports:
      - "49184:49184" #rtorrent
#      - "5000:5000" #SCGI port (UNUSED FOR NOW)
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${DOMAIN_FLOOD}"
      - "traefik.port=3000"
      - "traefik.docker.network=proxy"
      - "traefik.backend=flood"
      - "traefik.frontend.auth.basic.users=${FLOOD_LOGIN}"
      - "traefik.frontend.entryPoints=http,https"
    environment: #ENVIRONMENT VARIABLE
      - UID=${PUID}
      - GID=${PGID}
      - TZ=${TZ}
      - FLOOD_SECRET=${FLOOD_SECRET}
      - RTORRENT_SCGI=5000
      - "PKG_CONFIG_PATH=/usr/local/lib/pkgconfig" #Don't touch
    tty: true
    volumes:
        - ${FLOOD_PATH_CONFIG}:/flood-db
        - ${FLOOD_PATH_DOWNLOAD}:/data
    restart: always

networks:
  proxy:
    external:
      name: proxy
  default:
    driver: bridge
```
