### ISSUE TITLE
editable rtorrent.rc

### ISSUE THREAD

**Issue by vincentbenzo** [Wonderfall/docker-rtorrent-flood#8]
I can't find a way to access and modify the rtorrent.rc. Having the ability to edit it would be nice.

**Comment by berbiche** [comment]
You can bind mount a volume to `/home/torrent/.rtorrent.rc`.
The bind mount needs read-write permissions (the default).

Example `docker-compose.yml`:
```yaml
# docker-compose.yml
---
version: '3.7'

services:
  rtorrent:
    image: wonderfall/rtorrent-flood:latest
    container_name: rtorrent
    restart: unless-stopped
    networks:
      - your_network
    ports:
      - your_port:mapping
    tty: true
    environment:
      - 'UID=${PUID:?Environment variable PUID not provided}'
      - 'GID=${PGID:?Environment variable PGID not provided}'
      - 'TZ=${TZ:?Environment variable TZ not provided}'
      - 'FLOOD_SECRET=${FLOOD_SECRET?Environment variable FLOOD_SECRET not provided}'
      #- RTORRENT_SCGI=5000
      #- WEBROOT=/rtorrent
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./rtorrent/rtorrent.rc:/home/torrent/.rtorrent.rc:rw
      #- ./rtorrent/config.d:/home/torrent/rtorrent/config.d:rw
      - flood-db:/flood-db
     # Not necessary to be an environment variable
      - ${DOWNLOAD_LOCATION}:/data

volumes:
  flood-db:
    ...

networks:
  your_network:
    ...
```

And the following `.env` file (values must be provided):
```bash
# .env
PUID=
PGID=
TZ=your_timezone
FLOOD_SECRET=
DOWNLOAD_LOCATION=
```

Variable expansion [documentation](https://docs.docker.com/compose/compose-file/#variable-substitution)
